In [5]:
import kagglehub
import pandas as pd
import os
import numpy as np

In [6]:

path = kagglehub.dataset_download("nimapourmoradi/dry-bean-dataset-classification")
print("Path to dataset files:", path)
files = os.listdir(path)
print("Files in dataset directory:", files)
csv_file = os.path.join(path, 'Dry_Bean_Dataset.csv')  
df = pd.read_csv(csv_file)


Path to dataset files: /home/ibnsuaidi/.cache/kagglehub/datasets/nimapourmoradi/dry-bean-dataset-classification/versions/1
Files in dataset directory: ['Dry_Bean_Dataset.csv']


In [7]:
df.head()


Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0  28395    610.291       208.178117       173.888747      1.197191   
1  28734    638.018       200.524796       182.734419      1.097356   
2  29380    624.110       212.826130       175.931143      1.209713   
3  30008    645.884       210.557999       182.516516      1.153638   
4  30140    620.134       201.847882       190.279279      1.060798   

   Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0      0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1      0.411785       29172     191.272751  0.783968  0.984986   0.887034   
2      0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3      0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4      0.333680       30417     195.896503  0.773098  0.990893   0.984877   

   Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  Class  
0     0.913358      0.007332      0.003147      0.834222      0.998724  SEKER  
1     0.953861      0.006979      0.003564      0.909851      0.998430  SEKER  
2     0.908774      0.007244      0.003048      0.825871      0.999066  SEKER  
3     0.928329      0.007017      0.003215      0.861794      0.994199  SEKER  
4     0.970516      0.006697      0.003665      0.941900      0.999166  SEKER

In [8]:
def Jumlah_outlier(df, kolom):
    Q1 = df[kolom].quantile(0.25)
    Q3 = df[kolom].quantile(0.75)
    iqr = Q3 - Q1
    lower_bound = Q1 - (1.5 * iqr)
    upper_bound = Q3 + (1.5 * iqr)
    return df[(df[kolom] < lower_bound) | (df[kolom] > upper_bound)].shape[0]


def persen_outlier(df, kolom):
    quartile_1 = df[kolom].quantile(0.25)
    quartile_3 = df[kolom].quantile(0.75)
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - 1.5 * iqr
    upper_bound = quartile_3 + 1.5 * iqr

    outliers = df[(df[kolom] < lower_bound) | (df[kolom] > upper_bound)]
    persentase_outlier = (outliers.shape[0] / df.shape[0]) * 100
    return persentase_outlier

Kolom = ['Area', 'Perimeter', 'MajorAxisLength', 'MinorAxisLength', 'AspectRation', 'Eccentricity', 'ConvexArea', 'EquivDiameter', 'Extent', 'Solidity', 'roundness', 'Compactness', 'ShapeFactor1', 'ShapeFactor2', 'ShapeFactor3', 'ShapeFactor4']

for col in Kolom:
    print(f"Jumlah Outlier pada Kolom {col} : {Jumlah_outlier(df, col)}")
    print(f"Persentase Outlier pada Kolom {col} : {persen_outlier(df, col)}%")
    print("---------------------------------------------")

Jumlah Outlier pada Kolom Area : 551
Persentase Outlier pada Kolom Area : 4.048196311806627%
---------------------------------------------
Jumlah Outlier pada Kolom Perimeter : 500
Persentase Outlier pada Kolom Perimeter : 3.673499375505106%
---------------------------------------------
Jumlah Outlier pada Kolom MajorAxisLength : 379
Persentase Outlier pada Kolom MajorAxisLength : 2.7845125266328705%
---------------------------------------------
Jumlah Outlier pada Kolom MinorAxisLength : 569
Persentase Outlier pada Kolom MinorAxisLength : 4.1804422893248105%
---------------------------------------------
Jumlah Outlier pada Kolom AspectRation : 473
Persentase Outlier pada Kolom AspectRation : 3.475130409227831%
---------------------------------------------
Jumlah Outlier pada Kolom Eccentricity : 843
Persentase Outlier pada Kolom Eccentricity : 6.193519947101609%
---------------------------------------------
Jumlah Outlier pada Kolom ConvexArea : 550
Persentase Outlier pada Kolom Conve

In [9]:
# handling outliers menggunakan metode IQR
def handle_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    # Menentukan batas bawah dan batas atas
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Mengganti nilai outlier dengan nilai batas atas atau batas bawah terdekat
    df[column] = np.where(df[column] < lower_bound, lower_bound, df[column])
    df[column] = np.where(df[column] > upper_bound, upper_bound, df[column])


Kolom_Hilang = ['Area', 'Perimeter', 'MajorAxisLength', 'MinorAxisLength', 'AspectRation', 'Eccentricity', 'ConvexArea', 'EquivDiameter', 'Extent', 'Solidity', 'roundness', 'Compactness', 'ShapeFactor1', 'ShapeFactor3', 'ShapeFactor4']

# handling outlier pada kolom yang memiliki nilai outlier
for column in Kolom_Hilang:
  handle_outliers_iqr(df, column)

In [10]:
Kolom = ['Area', 'Perimeter', 'MajorAxisLength', 'MinorAxisLength', 'AspectRation', 'Eccentricity', 'ConvexArea', 'EquivDiameter', 'Extent', 'Solidity', 'roundness', 'Compactness', 'ShapeFactor1', 'ShapeFactor2', 'ShapeFactor3', 'ShapeFactor4']

for col in Kolom:
    print(f"Jumlah Outlier pada Kolom {col} : {Jumlah_outlier(df, col)}")
    print(f"Persentase Outlier pada Kolom {col} : {persen_outlier(df, col)}%")
    print("---------------------------------------------")

Jumlah Outlier pada Kolom Area : 0
Persentase Outlier pada Kolom Area : 0.0%
---------------------------------------------
Jumlah Outlier pada Kolom Perimeter : 0
Persentase Outlier pada Kolom Perimeter : 0.0%
---------------------------------------------
Jumlah Outlier pada Kolom MajorAxisLength : 0
Persentase Outlier pada Kolom MajorAxisLength : 0.0%
---------------------------------------------
Jumlah Outlier pada Kolom MinorAxisLength : 0
Persentase Outlier pada Kolom MinorAxisLength : 0.0%
---------------------------------------------
Jumlah Outlier pada Kolom AspectRation : 0
Persentase Outlier pada Kolom AspectRation : 0.0%
---------------------------------------------
Jumlah Outlier pada Kolom Eccentricity : 0
Persentase Outlier pada Kolom Eccentricity : 0.0%
---------------------------------------------
Jumlah Outlier pada Kolom ConvexArea : 0
Persentase Outlier pada Kolom ConvexArea : 0.0%
---------------------------------------------
Jumlah Outlier pada Kolom EquivDiameter :

In [11]:
df.duplicated().sum()


np.int64(68)

In [12]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [13]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
df['Class']= label.fit_transform(df['Class'])

df.head()

print(df['Class'].value_counts())

Class
3    3546
6    2636
5    2027
4    1860
2    1630
0    1322
1     522
Name: count, dtype: int64



**DERMASON    3546 = 3**

**SIRA        2636 = 6**

**SEKER       2027 = 5**

**HOROZ       1928 = 4**

**CALI        1630 = 2**

**BARBUNYA    1322 = 0**

**BOMBAY       522 = 1**



In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
Kolom = ['Area', 'Perimeter', 'MajorAxisLength', 'MinorAxisLength', 'AspectRation', 'Eccentricity', 'ConvexArea', 'EquivDiameter', 'Extent', 'Solidity', 'roundness', 'Compactness', 'ShapeFactor1', 'ShapeFactor2', 'ShapeFactor3', 'ShapeFactor4']
scaled_data = scaler.fit_transform(df[Kolom])
df_scaled = pd.DataFrame(scaled_data, columns=Kolom)
df_scaled['Class'] = df['Class'].values
df_scaled.head()



(13543, 17)

In [18]:
df_scaled.shape

(13543, 17)

In [93]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_scaled.drop(columns='Class'), df_scaled['Class'], test_size=0.2, random_state=181)

In [90]:
from sklearn import svm


clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

In [91]:
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred)
print (cm)

[[243   0  18   0   2   1   7]
 [  0 108   0   0   0   0   0]
 [  3   0 302   0   4   0   3]
 [  0   0   0 679   0  10  34]
 [  1   0   4   4 332   0   5]
 [  1   0   0   8   0 395  16]
 [  1   0   0  45   5   7 471]]


In [92]:
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Precision:", metrics.precision_score(y_test, y_pred, average='micro'))
print("Recall:", metrics.recall_score(y_test, y_pred, average='micro'))
print("F1 Score:", metrics.f1_score(y_test, y_pred, average='micro'))

Accuracy: 0.9339239571797712
Precision: 0.9339239571797712
Recall: 0.9339239571797712
F1 Score: 0.9339239571797712
